### ISSUE TITLE
You haven't worked on this!

### ISSUE THREAD

**Issue by sethuster** [rizzza/elementis#1]
I have an issue of the fact that this isn't done.  WTH man? :8ball:

**Comment by rizzza** [comment]
@sethuster I was under the impression you weren't a fan of Capybara? Come over and take care of my kids for a few weeks, it'll be :ship:

**Comment by rizzza** [comment]
Create skeleton and configuration. https://github.com/rizzza/elementis/pull/2

![borat_great_success](https://cloud.githubusercontent.com/assets/14932234/11582513/08de6f66-9a0d-11e5-87a1-2e7576b12eee.jpg)
